package org.jboss.pressgangccms.restserver.entities;

// Generated Nov 10, 2011 6:05:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Cacheable;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Exception generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "Exception")
public class SkynetException implements java.io.Serializable
{
	private static final long serialVersionUID = 3433948802907020258L;
	private Integer exceptionId;
	private Date timestamp;
	private String details;
	private boolean expected;
	private String description;
	private String user;

	public SkynetException()
	{
	}

	public SkynetException(final String details, final boolean expected)
	{
		this.details = details;
		this.expected = expected;
	}

	public SkynetException(final String details, final boolean expected, final String description)
	{
		this.details = details;
		this.expected = expected;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ExceptionID", unique = true, nullable = false)
	public Integer getExceptionId()
	{
		return this.exceptionId;
	}

	public void setExceptionId(Integer exceptionId)
	{
		this.exceptionId = exceptionId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Timestamp", nullable = false, length = 19)
	@NotNull
	public Date getTimestamp()
	{
		return this.timestamp;
	}

	public void setTimestamp(final Date timestamp)
	{
		this.timestamp = timestamp;
	}

	@Column(name = "Details", nullable = false, length = 65535)
	@NotNull
	@Size(max = 65535)
	public String getDetails()
	{
		return this.details;
	}

	public void setDetails(final String details)
	{
		this.details = details;
	}

	@Column(name = "Expected", nullable = false)
	public boolean isExpected()
	{
		return this.expected;
	}

	public void setExpected(final boolean expected)
	{
		this.expected = expected;
	}

	@Column(name = "Description", length = 512)
	@Size(max = 512)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(final String description)
	{
		this.description = description;
	}
	
	@Column(name = "User", length = 45)
	@Size(max = 512)
	public String getUser()
	{
		return this.user;
	}

	public void setUser(final String user)
	{
		this.user = user;
	}
	
	@SuppressWarnings("unused")
	@PrePersist
	private void prePersist()
	{
		this.timestamp = new Date();
	}

}
