USE PressGangCCMS;

CREATE TABLE IF NOT EXISTS `RS_ENDPOINT` (`ENDPOINT_ID` BIGINT AUTO_INCREMENT NOT NULL, `ENDPOINT_METHOD` VARCHAR(255), `ENDPOINT_URL` VARCHAR(255) NOT NULL, `URL_REGEX` BOOLEAN NOT NULL, PRIMARY KEY (`ENDPOINT_ID`), UNIQUE (`ENDPOINT_URL`, `ENDPOINT_METHOD`))
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `RS_SCOPE` (`SCOPE_ID` BIGINT AUTO_INCREMENT NOT NULL, `SCOPE_NAME` VARCHAR(255) NOT NULL, PRIMARY KEY (`SCOPE_ID`), UNIQUE (`SCOPE_NAME`))
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `RS_SCOPE_RS_ENDPOINT` (`SCOPE_ID` BIGINT NOT NULL, `ENDPOINT_ID` BIGINT NOT NULL, PRIMARY KEY (`SCOPE_ID`, `ENDPOINT_ID`))
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

INSERT INTO RS_SCOPE (SCOPE_ID, SCOPE_NAME) VALUES (1, 'DEFAULT');

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (1, 'https://localhost:8443/testrestserver/rest/1/settings/rerenderTopic', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (2, 'https://localhost:8443/testrestserver/rest/1/expanddatatrunk/get/json', 'GET', FALSE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (3, 'https://localhost:8443/testrestserver/rest/1/user/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (4, 'https://localhost:8443/testrestserver/rest/1/user/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (5, 'https://localhost:8443/testrestserver/rest/1/users/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (6, 'https://localhost:8443/testrestserver/rest/1/users/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (7, 'https://localhost:8443/testrestserver/rest/1/user/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (8, 'https://localhost:8443/testrestserver/rest/1/users/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (9, 'https://localhost:8443/testrestserver/rest/1/user/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (10, 'https://localhost:8443/testrestserver/rest/1/users/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (11, 'https://localhost:8443/testrestserver/rest/1/user/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (12, 'https://localhost:8443/testrestserver/rest/1/users/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (13, 'https://localhost:8443/testrestserver/rest/1/user/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (14, 'https://localhost:8443/testrestserver/rest/1/user/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (15, 'https://localhost:8443/testrestserver/rest/1/users/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (16, 'https://localhost:8443/testrestserver/rest/1/users/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (17, 'https://localhost:8443/testrestserver/rest/1/user/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (18, 'https://localhost:8443/testrestserver/rest/1/users/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (19, 'https://localhost:8443/testrestserver/rest/1/user/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (20, 'https://localhost:8443/testrestserver/rest/1/users/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (21, 'https://localhost:8443/testrestserver/rest/1/user/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (22, 'https://localhost:8443/testrestserver/rest/1/users/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (23, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (24, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (25, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (26, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (27, 'https://localhost:8443/testrestserver/rest/1/stringconstant/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (28, 'https://localhost:8443/testrestserver/rest/1/stringconstants/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (29, 'https://localhost:8443/testrestserver/rest/1/stringconstant/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (30, 'https://localhost:8443/testrestserver/rest/1/stringconstants/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (31, 'https://localhost:8443/testrestserver/rest/1/stringconstant/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (32, 'https://localhost:8443/testrestserver/rest/1/stringconstants/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (33, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (34, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (35, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (36, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (37, 'https://localhost:8443/testrestserver/rest/1/stringconstant/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (38, 'https://localhost:8443/testrestserver/rest/1/stringconstants/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (39, 'https://localhost:8443/testrestserver/rest/1/stringconstant/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (40, 'https://localhost:8443/testrestserver/rest/1/stringconstants/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (41, 'https://localhost:8443/testrestserver/rest/1/stringconstant/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (42, 'https://localhost:8443/testrestserver/rest/1/stringconstants/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (43, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (44, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (45, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (46, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (47, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (48, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (49, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (50, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (51, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (52, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (53, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (54, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (55, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (56, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (57, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (58, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (59, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (60, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (61, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (62, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (63, 'https://localhost:8443/testrestserver/rest/1/role/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (64, 'https://localhost:8443/testrestserver/rest/1/role/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (65, 'https://localhost:8443/testrestserver/rest/1/roles/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (66, 'https://localhost:8443/testrestserver/rest/1/roles/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (67, 'https://localhost:8443/testrestserver/rest/1/role/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (68, 'https://localhost:8443/testrestserver/rest/1/roles/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (69, 'https://localhost:8443/testrestserver/rest/1/role/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (70, 'https://localhost:8443/testrestserver/rest/1/roles/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (71, 'https://localhost:8443/testrestserver/rest/1/role/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (72, 'https://localhost:8443/testrestserver/rest/1/roles/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (73, 'https://localhost:8443/testrestserver/rest/1/role/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (74, 'https://localhost:8443/testrestserver/rest/1/role/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (75, 'https://localhost:8443/testrestserver/rest/1/roles/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (76, 'https://localhost:8443/testrestserver/rest/1/roles/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (77, 'https://localhost:8443/testrestserver/rest/1/role/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (78, 'https://localhost:8443/testrestserver/rest/1/roles/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (79, 'https://localhost:8443/testrestserver/rest/1/role/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (80, 'https://localhost:8443/testrestserver/rest/1/roles/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (81, 'https://localhost:8443/testrestserver/rest/1/role/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (82, 'https://localhost:8443/testrestserver/rest/1/roles/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (83, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (84, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (85, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (86, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (87, 'https://localhost:8443/testrestserver/rest/1/propertytag/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (88, 'https://localhost:8443/testrestserver/rest/1/propertytags/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (89, 'https://localhost:8443/testrestserver/rest/1/propertytag/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (90, 'https://localhost:8443/testrestserver/rest/1/propertytags/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (91, 'https://localhost:8443/testrestserver/rest/1/propertytag/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (92, 'https://localhost:8443/testrestserver/rest/1/propertytags/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (93, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (94, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (95, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (96, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (97, 'https://localhost:8443/testrestserver/rest/1/propertytag/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (98, 'https://localhost:8443/testrestserver/rest/1/propertytags/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (99, 'https://localhost:8443/testrestserver/rest/1/propertytag/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (100, 'https://localhost:8443/testrestserver/rest/1/propertytags/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (101, 'https://localhost:8443/testrestserver/rest/1/propertytag/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (102, 'https://localhost:8443/testrestserver/rest/1/propertytags/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (103, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (104, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (105, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (106, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (107, 'https://localhost:8443/testrestserver/rest/1/propertycategory/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (108, 'https://localhost:8443/testrestserver/rest/1/propertycategories/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (109, 'https://localhost:8443/testrestserver/rest/1/propertycategory/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (110, 'https://localhost:8443/testrestserver/rest/1/propertycategories/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (111, 'https://localhost:8443/testrestserver/rest/1/propertycategory/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (112, 'https://localhost:8443/testrestserver/rest/1/propertycategories/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (113, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (114, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (115, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (116, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (117, 'https://localhost:8443/testrestserver/rest/1/propertycategory/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (118, 'https://localhost:8443/testrestserver/rest/1/propertycategories/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (119, 'https://localhost:8443/testrestserver/rest/1/propertycategory/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (120, 'https://localhost:8443/testrestserver/rest/1/propertycategories/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (121, 'https://localhost:8443/testrestserver/rest/1/propertycategory/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (122, 'https://localhost:8443/testrestserver/rest/1/propertycategories/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (123, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (124, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (125, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (126, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (127, 'https://localhost:8443/testrestserver/rest/1/blobconstant/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (128, 'https://localhost:8443/testrestserver/rest/1/blobconstants/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (129, 'https://localhost:8443/testrestserver/rest/1/blobconstant/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (130, 'https://localhost:8443/testrestserver/rest/1/blobconstants/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (131, 'https://localhost:8443/testrestserver/rest/1/blobconstant/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (132, 'https://localhost:8443/testrestserver/rest/1/blobconstants/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (133, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (134, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (135, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (136, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (137, 'https://localhost:8443/testrestserver/rest/1/blobconstant/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (138, 'https://localhost:8443/testrestserver/rest/1/blobconstants/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (139, 'https://localhost:8443/testrestserver/rest/1/blobconstant/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (140, 'https://localhost:8443/testrestserver/rest/1/blobconstants/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (141, 'https://localhost:8443/testrestserver/rest/1/blobconstant/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (142, 'https://localhost:8443/testrestserver/rest/1/blobconstants/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (143, 'https://localhost:8443/testrestserver/rest/1/project/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (144, 'https://localhost:8443/testrestserver/rest/1/project/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (145, 'https://localhost:8443/testrestserver/rest/1/projects/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (146, 'https://localhost:8443/testrestserver/rest/1/projects/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (147, 'https://localhost:8443/testrestserver/rest/1/project/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (148, 'https://localhost:8443/testrestserver/rest/1/projects/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (149, 'https://localhost:8443/testrestserver/rest/1/project/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (150, 'https://localhost:8443/testrestserver/rest/1/projects/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (151, 'https://localhost:8443/testrestserver/rest/1/project/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (152, 'https://localhost:8443/testrestserver/rest/1/projects/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (153, 'https://localhost:8443/testrestserver/rest/1/project/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (154, 'https://localhost:8443/testrestserver/rest/1/project/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (155, 'https://localhost:8443/testrestserver/rest/1/projects/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (156, 'https://localhost:8443/testrestserver/rest/1/projects/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (157, 'https://localhost:8443/testrestserver/rest/1/project/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (158, 'https://localhost:8443/testrestserver/rest/1/projects/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (159, 'https://localhost:8443/testrestserver/rest/1/project/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (160, 'https://localhost:8443/testrestserver/rest/1/projects/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (161, 'https://localhost:8443/testrestserver/rest/1/project/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (162, 'https://localhost:8443/testrestserver/rest/1/projects/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (163, 'https://localhost:8443/testrestserver/rest/1/tag/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (164, 'https://localhost:8443/testrestserver/rest/1/tag/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (165, 'https://localhost:8443/testrestserver/rest/1/tags/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (166, 'https://localhost:8443/testrestserver/rest/1/tags/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (167, 'https://localhost:8443/testrestserver/rest/1/tag/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (168, 'https://localhost:8443/testrestserver/rest/1/tags/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (169, 'https://localhost:8443/testrestserver/rest/1/tag/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (170, 'https://localhost:8443/testrestserver/rest/1/tags/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (171, 'https://localhost:8443/testrestserver/rest/1/tag/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (172, 'https://localhost:8443/testrestserver/rest/1/tags/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (173, 'https://localhost:8443/testrestserver/rest/1/tag/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (174, 'https://localhost:8443/testrestserver/rest/1/tag/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (175, 'https://localhost:8443/testrestserver/rest/1/tags/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (176, 'https://localhost:8443/testrestserver/rest/1/tags/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (177, 'https://localhost:8443/testrestserver/rest/1/tag/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (178, 'https://localhost:8443/testrestserver/rest/1/tags/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (179, 'https://localhost:8443/testrestserver/rest/1/tag/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (180, 'https://localhost:8443/testrestserver/rest/1/tags/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (181, 'https://localhost:8443/testrestserver/rest/1/tag/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (182, 'https://localhost:8443/testrestserver/rest/1/tags/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (183, 'https://localhost:8443/testrestserver/rest/1/category/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (184, 'https://localhost:8443/testrestserver/rest/1/category/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (185, 'https://localhost:8443/testrestserver/rest/1/categories/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (186, 'https://localhost:8443/testrestserver/rest/1/categories/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (187, 'https://localhost:8443/testrestserver/rest/1/category/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (188, 'https://localhost:8443/testrestserver/rest/1/categories/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (189, 'https://localhost:8443/testrestserver/rest/1/category/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (190, 'https://localhost:8443/testrestserver/rest/1/categories/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (191, 'https://localhost:8443/testrestserver/rest/1/category/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (192, 'https://localhost:8443/testrestserver/rest/1/categories/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (193, 'https://localhost:8443/testrestserver/rest/1/category/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (194, 'https://localhost:8443/testrestserver/rest/1/category/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (195, 'https://localhost:8443/testrestserver/rest/1/categories/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (196, 'https://localhost:8443/testrestserver/rest/1/categories/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (197, 'https://localhost:8443/testrestserver/rest/1/category/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (198, 'https://localhost:8443/testrestserver/rest/1/categories/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (199, 'https://localhost:8443/testrestserver/rest/1/category/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (200, 'https://localhost:8443/testrestserver/rest/1/categories/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (201, 'https://localhost:8443/testrestserver/rest/1/category/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (202, 'https://localhost:8443/testrestserver/rest/1/categories/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (203, 'https://localhost:8443/testrestserver/rest/1/image/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (204, 'https://localhost:8443/testrestserver/rest/1/image/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (205, 'https://localhost:8443/testrestserver/rest/1/images/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (206, 'https://localhost:8443/testrestserver/rest/1/images/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (207, 'https://localhost:8443/testrestserver/rest/1/image/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (208, 'https://localhost:8443/testrestserver/rest/1/images/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (209, 'https://localhost:8443/testrestserver/rest/1/image/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (210, 'https://localhost:8443/testrestserver/rest/1/images/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (211, 'https://localhost:8443/testrestserver/rest/1/image/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (212, 'https://localhost:8443/testrestserver/rest/1/images/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (213, 'https://localhost:8443/testrestserver/rest/1/image/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (214, 'https://localhost:8443/testrestserver/rest/1/image/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (215, 'https://localhost:8443/testrestserver/rest/1/images/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (216, 'https://localhost:8443/testrestserver/rest/1/images/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (217, 'https://localhost:8443/testrestserver/rest/1/image/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (218, 'https://localhost:8443/testrestserver/rest/1/images/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (219, 'https://localhost:8443/testrestserver/rest/1/image/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (220, 'https://localhost:8443/testrestserver/rest/1/images/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (221, 'https://localhost:8443/testrestserver/rest/1/image/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (222, 'https://localhost:8443/testrestserver/rest/1/images/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (223, 'https://localhost:8443/testrestserver/rest/1/image/get/raw/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (224, 'https://localhost:8443/testrestserver/rest/1/image/get/raw/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (225, 'https://localhost:8443/testrestserver/rest/1/image/get/raw/\\d+/thumbnail', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (226, 'https://localhost:8443/testrestserver/rest/1/topic/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (227, 'https://localhost:8443/testrestserver/rest/1/topic/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (228, 'https://localhost:8443/testrestserver/rest/1/topics/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (229, 'https://localhost:8443/testrestserver/rest/1/topics/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (230, 'https://localhost:8443/testrestserver/rest/1/topic/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (231, 'https://localhost:8443/testrestserver/rest/1/topics/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (232, 'https://localhost:8443/testrestserver/rest/1/topic/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (233, 'https://localhost:8443/testrestserver/rest/1/topics/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (234, 'https://localhost:8443/testrestserver/rest/1/topic/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (235, 'https://localhost:8443/testrestserver/rest/1/topics/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (236, 'https://localhost:8443/testrestserver/rest/1/topic/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (237, 'https://localhost:8443/testrestserver/rest/1/topic/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (238, 'https://localhost:8443/testrestserver/rest/1/topics/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (239, 'https://localhost:8443/testrestserver/rest/1/topics/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (240, 'https://localhost:8443/testrestserver/rest/1/topic/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (241, 'https://localhost:8443/testrestserver/rest/1/topics/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (242, 'https://localhost:8443/testrestserver/rest/1/topic/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (243, 'https://localhost:8443/testrestserver/rest/1/topics/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (244, 'https://localhost:8443/testrestserver/rest/1/topic/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (245, 'https://localhost:8443/testrestserver/rest/1/topics/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (246, 'https://localhost:8443/testrestserver/rest/1/topics/get/xml/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (247, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (248, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (249, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\\d+/xml', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (250, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\\d+/r/\\d+/xml', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (251, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\\d+/xmlContainedIn', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (252, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\\d+/xmlNoContainer', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (253, 'https://localhost:8443/testrestserver/rest/1/topic/get/html/\\d+/html', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (254, 'https://localhost:8443/testrestserver/rest/1/topic/get/html/\\d+/r/\\d+/html', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (255, 'https://localhost:8443/testrestserver/rest/1/topics/get/atom/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (256, 'https://localhost:8443/testrestserver/rest/1/filter/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (257, 'https://localhost:8443/testrestserver/rest/1/filter/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (258, 'https://localhost:8443/testrestserver/rest/1/filters/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (259, 'https://localhost:8443/testrestserver/rest/1/filters/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (260, 'https://localhost:8443/testrestserver/rest/1/filter/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (261, 'https://localhost:8443/testrestserver/rest/1/filters/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (262, 'https://localhost:8443/testrestserver/rest/1/filter/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (263, 'https://localhost:8443/testrestserver/rest/1/filters/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (264, 'https://localhost:8443/testrestserver/rest/1/filter/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (265, 'https://localhost:8443/testrestserver/rest/1/filters/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (266, 'https://localhost:8443/testrestserver/rest/1/filter/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (267, 'https://localhost:8443/testrestserver/rest/1/filter/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (268, 'https://localhost:8443/testrestserver/rest/1/filters/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (269, 'https://localhost:8443/testrestserver/rest/1/filters/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (270, 'https://localhost:8443/testrestserver/rest/1/filter/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (271, 'https://localhost:8443/testrestserver/rest/1/filters/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (272, 'https://localhost:8443/testrestserver/rest/1/filter/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (273, 'https://localhost:8443/testrestserver/rest/1/filters/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (274, 'https://localhost:8443/testrestserver/rest/1/filter/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (275, 'https://localhost:8443/testrestserver/rest/1/filters/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (276, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (277, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (278, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (279, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (280, 'https://localhost:8443/testrestserver/rest/1/integerconstant/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (281, 'https://localhost:8443/testrestserver/rest/1/integerconstants/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (282, 'https://localhost:8443/testrestserver/rest/1/integerconstant/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (283, 'https://localhost:8443/testrestserver/rest/1/integerconstants/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (284, 'https://localhost:8443/testrestserver/rest/1/integerconstant/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (285, 'https://localhost:8443/testrestserver/rest/1/integerconstants/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (286, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (287, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (288, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (289, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (290, 'https://localhost:8443/testrestserver/rest/1/integerconstant/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (291, 'https://localhost:8443/testrestserver/rest/1/integerconstants/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (292, 'https://localhost:8443/testrestserver/rest/1/integerconstant/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (293, 'https://localhost:8443/testrestserver/rest/1/integerconstants/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (294, 'https://localhost:8443/testrestserver/rest/1/integerconstant/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (295, 'https://localhost:8443/testrestserver/rest/1/integerconstants/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (296, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (297, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (298, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (299, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (300, 'https://localhost:8443/testrestserver/rest/1/contentspec/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (301, 'https://localhost:8443/testrestserver/rest/1/contentspecs/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (302, 'https://localhost:8443/testrestserver/rest/1/contentspec/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (303, 'https://localhost:8443/testrestserver/rest/1/contentspecs/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (304, 'https://localhost:8443/testrestserver/rest/1/contentspec/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (305, 'https://localhost:8443/testrestserver/rest/1/contentspecs/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (306, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (307, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (308, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (309, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (310, 'https://localhost:8443/testrestserver/rest/1/contentspec/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (311, 'https://localhost:8443/testrestserver/rest/1/contentspecs/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (312, 'https://localhost:8443/testrestserver/rest/1/contentspec/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (313, 'https://localhost:8443/testrestserver/rest/1/contentspecs/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (314, 'https://localhost:8443/testrestserver/rest/1/contentspec/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (315, 'https://localhost:8443/testrestserver/rest/1/contentspecs/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (316, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (317, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (318, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (319, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (320, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (321, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (322, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (323, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (324, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (325, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (326, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (327, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (328, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (329, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (330, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (331, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (332, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (333, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (334, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (335, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (336, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/get/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (337, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/get/jsonp/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (338, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/get/jsonp/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (339, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/get/jsonp/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (340, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (341, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/update/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (342, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (343, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/create/jsonp', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (344, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/delete/jsonp/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (345, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/delete/jsonp/ids;(\\d+;)*\\d+;?', 'GET', TRUE);

INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (346, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/get/json/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (347, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/get/json/\\d+/r/\\d+', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (348, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/get/json/all', 'GET', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (349, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/get/json/query;([-\\w%~\\.]+=[-\\w%~\\.]*;)*([-\\w%~\\.]+=[-\\w%~\\.]*;?)?', 'GET', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (350, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (351, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/update/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (352, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (353, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/create/json', 'POST', FALSE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (354, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednode/delete/json/\\d+', 'DELETE', TRUE);
INSERT INTO RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) VALUES (355, 'https://localhost:8443/testrestserver/rest/1/contentspectranslatednodes/delete/json/ids;(\\d+;)*\\d+;?', 'DELETE', TRUE);

INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 1);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 2);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 3);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 4);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 5);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 6);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 7);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 8);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 9);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 10);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 11);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 12);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 13);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 14);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 15);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 16);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 17);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 18);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 19);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 20);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 21);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 22);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 23);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 24);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 25);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 26);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 27);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 28);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 29);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 30);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 31);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 32);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 33);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 34);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 35);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 36);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 37);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 38);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 39);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 40);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 41);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 42);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 43);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 44);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 45);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 46);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 47);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 48);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 49);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 50);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 51);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 52);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 53);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 54);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 55);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 56);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 57);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 58);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 59);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 60);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 61);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 62);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 63);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 64);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 65);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 66);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 67);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 68);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 69);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 70);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 71);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 72);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 73);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 74);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 75);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 76);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 77);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 78);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 79);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 80);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 81);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 82);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 83);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 84);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 85);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 86);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 87);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 88);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 89);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 90);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 91);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 92);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 93);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 94);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 95);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 96);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 97);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 98);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 99);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 100);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 101);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 102);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 103);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 104);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 105);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 106);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 107);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 108);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 109);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 110);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 111);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 112);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 113);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 114);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 115);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 116);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 117);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 118);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 119);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 120);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 121);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 122);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 123);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 124);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 125);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 126);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 127);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 128);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 129);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 130);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 131);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 132);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 133);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 134);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 135);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 136);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 137);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 138);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 139);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 140);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 141);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 142);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 143);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 144);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 145);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 146);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 147);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 148);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 149);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 150);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 151);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 152);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 153);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 154);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 155);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 156);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 157);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 158);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 159);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 160);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 161);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 162);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 163);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 164);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 165);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 166);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 167);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 168);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 169);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 170);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 171);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 172);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 173);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 174);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 175);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 176);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 177);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 178);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 179);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 180);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 181);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 182);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 183);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 184);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 185);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 186);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 187);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 188);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 189);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 190);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 191);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 192);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 193);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 194);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 195);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 196);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 197);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 198);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 199);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 200);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 201);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 202);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 203);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 204);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 205);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 206);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 207);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 208);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 209);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 210);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 211);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 212);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 213);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 214);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 215);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 216);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 217);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 218);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 219);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 220);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 221);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 222);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 223);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 224);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 225);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 226);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 227);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 228);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 229);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 230);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 231);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 232);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 233);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 234);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 235);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 236);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 237);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 238);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 239);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 240);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 241);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 242);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 243);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 244);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 245);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 246);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 247);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 248);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 249);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 250);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 251);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 252);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 253);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 254);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 255);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 256);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 257);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 258);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 259);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 260);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 261);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 262);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 263);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 264);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 265);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 266);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 267);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 268);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 269);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 270);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 271);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 272);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 273);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 274);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 275);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 276);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 277);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 278);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 279);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 280);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 281);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 282);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 283);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 284);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 285);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 286);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 287);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 288);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 289);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 290);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 291);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 292);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 293);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 294);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 295);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 296);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 297);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 298);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 299);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 300);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 301);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 302);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 303);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 304);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 305);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 306);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 307);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 308);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 309);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 310);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 311);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 312);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 313);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 314);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 315);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 316);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 317);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 318);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 319);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 320);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 321);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 322);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 323);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 324);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 325);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 326);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 327);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 328);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 329);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 330);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 331);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 332);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 333);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 334);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 335);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 336);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 337);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 338);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 339);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 340);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 341);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 342);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 343);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 344);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 345);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 346);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 347);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 348);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 349);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 350);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 351);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 352);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 353);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 354);
INSERT INTO RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) VALUES (1, 355);

ALTER TABLE `RS_SCOPE_RS_ENDPOINT` ADD CONSTRAINT `FK_RS_SCOPE_RS_ENDPOINT_SCOPE_ID` FOREIGN KEY (`SCOPE_ID`) REFERENCES `RS_SCOPE` (`SCOPE_ID`), ADD CONSTRAINT `FK_RS_SCOPE_RS_ENDPOINT_ENDPOINT_ID` FOREIGN KEY (`ENDPOINT_ID`) REFERENCES `RS_ENDPOINT` (`ENDPOINT_ID`);
