use PressGangCCMS;

create table if not exists `RS_ENDPOINT` (`ENDPOINT_ID` bigint auto_increment not null, `ENDPOINT_METHOD` varchar(255), `ENDPOINT_URL` varchar(255) not null, `URL_REGEX` boolean not null, primary key (`ENDPOINT_ID`), unique (`ENDPOINT_URL`, `ENDPOINT_METHOD`)) engine=InnoDB default charset=utf8;

create table if not exists `RS_SCOPE` (`SCOPE_ID` bigint auto_increment not null, `SCOPE_NAME` varchar(255) not null, primary key (`SCOPE_ID`), unique (`SCOPE_NAME`)) engine=InnoDB default charset=utf8;

create table if not exists `RS_SCOPE_RS_ENDPOINT` (`SCOPE_ID` bigint not null, `ENDPOINT_ID` bigint not null, primary key (`SCOPE_ID`, `ENDPOINT_ID`)) engine=InnoDB default charset=utf8;

insert into RS_SCOPE (SCOPE_ID, SCOPE_NAME) values (1, 'DEFAULT');

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (1, 'https://localhost:8443/testrestserver/rest/1/settings/rerenderTopic', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (2, 'https://localhost:8443/testrestserver/rest/1/expanddatatrunk/get/json', 'GET', false);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (3, 'https://localhost:8443/testrestserver/rest/1/user/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (4, 'https://localhost:8443/testrestserver/rest/1/user/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (5, 'https://localhost:8443/testrestserver/rest/1/users/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (6, 'https://localhost:8443/testrestserver/rest/1/users/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (7, 'https://localhost:8443/testrestserver/rest/1/user/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (8, 'https://localhost:8443/testrestserver/rest/1/users/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (9, 'https://localhost:8443/testrestserver/rest/1/user/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (10, 'https://localhost:8443/testrestserver/rest/1/users/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (11, 'https://localhost:8443/testrestserver/rest/1/user/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (12, 'https://localhost:8443/testrestserver/rest/1/users/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (13, 'https://localhost:8443/testrestserver/rest/1/user/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (14, 'https://localhost:8443/testrestserver/rest/1/user/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (15, 'https://localhost:8443/testrestserver/rest/1/users/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (16, 'https://localhost:8443/testrestserver/rest/1/users/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (17, 'https://localhost:8443/testrestserver/rest/1/user/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (18, 'https://localhost:8443/testrestserver/rest/1/users/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (19, 'https://localhost:8443/testrestserver/rest/1/user/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (20, 'https://localhost:8443/testrestserver/rest/1/users/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (21, 'https://localhost:8443/testrestserver/rest/1/user/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (22, 'https://localhost:8443/testrestserver/rest/1/users/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (23, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (24, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (25, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (26, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (27, 'https://localhost:8443/testrestserver/rest/1/stringconstant/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (28, 'https://localhost:8443/testrestserver/rest/1/stringconstants/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (29, 'https://localhost:8443/testrestserver/rest/1/stringconstant/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (30, 'https://localhost:8443/testrestserver/rest/1/stringconstants/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (31, 'https://localhost:8443/testrestserver/rest/1/stringconstant/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (32, 'https://localhost:8443/testrestserver/rest/1/stringconstants/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (33, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (34, 'https://localhost:8443/testrestserver/rest/1/stringconstant/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (35, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (36, 'https://localhost:8443/testrestserver/rest/1/stringconstants/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (37, 'https://localhost:8443/testrestserver/rest/1/stringconstant/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (38, 'https://localhost:8443/testrestserver/rest/1/stringconstants/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (39, 'https://localhost:8443/testrestserver/rest/1/stringconstant/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (40, 'https://localhost:8443/testrestserver/rest/1/stringconstants/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (41, 'https://localhost:8443/testrestserver/rest/1/stringconstant/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (42, 'https://localhost:8443/testrestserver/rest/1/stringconstants/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (43, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (44, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (45, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (46, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (47, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (48, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (49, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (50, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (51, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (52, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (53, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (54, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (55, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (56, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (57, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (58, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (59, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (60, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (61, 'https://localhost:8443/testrestserver/rest/1/translatedtopic/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (62, 'https://localhost:8443/testrestserver/rest/1/translatedtopics/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (63, 'https://localhost:8443/testrestserver/rest/1/role/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (64, 'https://localhost:8443/testrestserver/rest/1/role/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (65, 'https://localhost:8443/testrestserver/rest/1/roles/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (66, 'https://localhost:8443/testrestserver/rest/1/roles/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (67, 'https://localhost:8443/testrestserver/rest/1/role/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (68, 'https://localhost:8443/testrestserver/rest/1/roles/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (69, 'https://localhost:8443/testrestserver/rest/1/role/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (70, 'https://localhost:8443/testrestserver/rest/1/roles/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (71, 'https://localhost:8443/testrestserver/rest/1/role/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (72, 'https://localhost:8443/testrestserver/rest/1/roles/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (73, 'https://localhost:8443/testrestserver/rest/1/role/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (74, 'https://localhost:8443/testrestserver/rest/1/role/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (75, 'https://localhost:8443/testrestserver/rest/1/roles/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (76, 'https://localhost:8443/testrestserver/rest/1/roles/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (77, 'https://localhost:8443/testrestserver/rest/1/role/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (78, 'https://localhost:8443/testrestserver/rest/1/roles/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (79, 'https://localhost:8443/testrestserver/rest/1/role/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (80, 'https://localhost:8443/testrestserver/rest/1/roles/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (81, 'https://localhost:8443/testrestserver/rest/1/role/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (82, 'https://localhost:8443/testrestserver/rest/1/roles/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (83, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (84, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (85, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (86, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (87, 'https://localhost:8443/testrestserver/rest/1/propertytag/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (88, 'https://localhost:8443/testrestserver/rest/1/propertytags/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (89, 'https://localhost:8443/testrestserver/rest/1/propertytag/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (90, 'https://localhost:8443/testrestserver/rest/1/propertytags/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (91, 'https://localhost:8443/testrestserver/rest/1/propertytag/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (92, 'https://localhost:8443/testrestserver/rest/1/propertytags/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (93, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (94, 'https://localhost:8443/testrestserver/rest/1/propertytag/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (95, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (96, 'https://localhost:8443/testrestserver/rest/1/propertytags/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (97, 'https://localhost:8443/testrestserver/rest/1/propertytag/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (98, 'https://localhost:8443/testrestserver/rest/1/propertytags/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (99, 'https://localhost:8443/testrestserver/rest/1/propertytag/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (100, 'https://localhost:8443/testrestserver/rest/1/propertytags/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (101, 'https://localhost:8443/testrestserver/rest/1/propertytag/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (102, 'https://localhost:8443/testrestserver/rest/1/propertytags/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (103, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (104, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (105, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (106, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (107, 'https://localhost:8443/testrestserver/rest/1/propertycategory/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (108, 'https://localhost:8443/testrestserver/rest/1/propertycategories/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (109, 'https://localhost:8443/testrestserver/rest/1/propertycategory/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (110, 'https://localhost:8443/testrestserver/rest/1/propertycategories/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (111, 'https://localhost:8443/testrestserver/rest/1/propertycategory/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (112, 'https://localhost:8443/testrestserver/rest/1/propertycategories/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (113, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (114, 'https://localhost:8443/testrestserver/rest/1/propertycategory/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (115, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (116, 'https://localhost:8443/testrestserver/rest/1/propertycategories/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (117, 'https://localhost:8443/testrestserver/rest/1/propertycategory/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (118, 'https://localhost:8443/testrestserver/rest/1/propertycategories/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (119, 'https://localhost:8443/testrestserver/rest/1/propertycategory/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (120, 'https://localhost:8443/testrestserver/rest/1/propertycategories/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (121, 'https://localhost:8443/testrestserver/rest/1/propertycategory/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (122, 'https://localhost:8443/testrestserver/rest/1/propertycategories/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (123, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (124, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (125, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (126, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (127, 'https://localhost:8443/testrestserver/rest/1/blobconstant/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (128, 'https://localhost:8443/testrestserver/rest/1/blobconstants/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (129, 'https://localhost:8443/testrestserver/rest/1/blobconstant/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (130, 'https://localhost:8443/testrestserver/rest/1/blobconstants/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (131, 'https://localhost:8443/testrestserver/rest/1/blobconstant/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (132, 'https://localhost:8443/testrestserver/rest/1/blobconstants/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (133, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (134, 'https://localhost:8443/testrestserver/rest/1/blobconstant/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (135, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (136, 'https://localhost:8443/testrestserver/rest/1/blobconstants/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (137, 'https://localhost:8443/testrestserver/rest/1/blobconstant/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (138, 'https://localhost:8443/testrestserver/rest/1/blobconstants/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (139, 'https://localhost:8443/testrestserver/rest/1/blobconstant/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (140, 'https://localhost:8443/testrestserver/rest/1/blobconstants/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (141, 'https://localhost:8443/testrestserver/rest/1/blobconstant/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (142, 'https://localhost:8443/testrestserver/rest/1/blobconstants/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (143, 'https://localhost:8443/testrestserver/rest/1/project/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (144, 'https://localhost:8443/testrestserver/rest/1/project/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (145, 'https://localhost:8443/testrestserver/rest/1/projects/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (146, 'https://localhost:8443/testrestserver/rest/1/projects/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (147, 'https://localhost:8443/testrestserver/rest/1/project/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (148, 'https://localhost:8443/testrestserver/rest/1/projects/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (149, 'https://localhost:8443/testrestserver/rest/1/project/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (150, 'https://localhost:8443/testrestserver/rest/1/projects/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (151, 'https://localhost:8443/testrestserver/rest/1/project/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (152, 'https://localhost:8443/testrestserver/rest/1/projects/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (153, 'https://localhost:8443/testrestserver/rest/1/project/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (154, 'https://localhost:8443/testrestserver/rest/1/project/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (155, 'https://localhost:8443/testrestserver/rest/1/projects/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (156, 'https://localhost:8443/testrestserver/rest/1/projects/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (157, 'https://localhost:8443/testrestserver/rest/1/project/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (158, 'https://localhost:8443/testrestserver/rest/1/projects/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (159, 'https://localhost:8443/testrestserver/rest/1/project/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (160, 'https://localhost:8443/testrestserver/rest/1/projects/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (161, 'https://localhost:8443/testrestserver/rest/1/project/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (162, 'https://localhost:8443/testrestserver/rest/1/projects/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (163, 'https://localhost:8443/testrestserver/rest/1/tag/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (164, 'https://localhost:8443/testrestserver/rest/1/tag/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (165, 'https://localhost:8443/testrestserver/rest/1/tags/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (166, 'https://localhost:8443/testrestserver/rest/1/tags/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (167, 'https://localhost:8443/testrestserver/rest/1/tag/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (168, 'https://localhost:8443/testrestserver/rest/1/tags/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (169, 'https://localhost:8443/testrestserver/rest/1/tag/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (170, 'https://localhost:8443/testrestserver/rest/1/tags/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (171, 'https://localhost:8443/testrestserver/rest/1/tag/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (172, 'https://localhost:8443/testrestserver/rest/1/tags/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (173, 'https://localhost:8443/testrestserver/rest/1/tag/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (174, 'https://localhost:8443/testrestserver/rest/1/tag/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (175, 'https://localhost:8443/testrestserver/rest/1/tags/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (176, 'https://localhost:8443/testrestserver/rest/1/tags/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (177, 'https://localhost:8443/testrestserver/rest/1/tag/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (178, 'https://localhost:8443/testrestserver/rest/1/tags/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (179, 'https://localhost:8443/testrestserver/rest/1/tag/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (180, 'https://localhost:8443/testrestserver/rest/1/tags/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (181, 'https://localhost:8443/testrestserver/rest/1/tag/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (182, 'https://localhost:8443/testrestserver/rest/1/tags/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (183, 'https://localhost:8443/testrestserver/rest/1/category/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (184, 'https://localhost:8443/testrestserver/rest/1/category/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (185, 'https://localhost:8443/testrestserver/rest/1/categories/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (186, 'https://localhost:8443/testrestserver/rest/1/categories/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (187, 'https://localhost:8443/testrestserver/rest/1/category/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (188, 'https://localhost:8443/testrestserver/rest/1/categories/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (189, 'https://localhost:8443/testrestserver/rest/1/category/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (190, 'https://localhost:8443/testrestserver/rest/1/categories/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (191, 'https://localhost:8443/testrestserver/rest/1/category/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (192, 'https://localhost:8443/testrestserver/rest/1/categories/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (193, 'https://localhost:8443/testrestserver/rest/1/category/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (194, 'https://localhost:8443/testrestserver/rest/1/category/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (195, 'https://localhost:8443/testrestserver/rest/1/categories/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (196, 'https://localhost:8443/testrestserver/rest/1/categories/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (197, 'https://localhost:8443/testrestserver/rest/1/category/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (198, 'https://localhost:8443/testrestserver/rest/1/categories/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (199, 'https://localhost:8443/testrestserver/rest/1/category/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (200, 'https://localhost:8443/testrestserver/rest/1/categories/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (201, 'https://localhost:8443/testrestserver/rest/1/category/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (202, 'https://localhost:8443/testrestserver/rest/1/categories/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (203, 'https://localhost:8443/testrestserver/rest/1/image/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (204, 'https://localhost:8443/testrestserver/rest/1/image/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (205, 'https://localhost:8443/testrestserver/rest/1/images/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (206, 'https://localhost:8443/testrestserver/rest/1/images/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (207, 'https://localhost:8443/testrestserver/rest/1/image/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (208, 'https://localhost:8443/testrestserver/rest/1/images/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (209, 'https://localhost:8443/testrestserver/rest/1/image/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (210, 'https://localhost:8443/testrestserver/rest/1/images/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (211, 'https://localhost:8443/testrestserver/rest/1/image/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (212, 'https://localhost:8443/testrestserver/rest/1/images/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (213, 'https://localhost:8443/testrestserver/rest/1/image/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (214, 'https://localhost:8443/testrestserver/rest/1/image/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (215, 'https://localhost:8443/testrestserver/rest/1/images/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (216, 'https://localhost:8443/testrestserver/rest/1/images/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (217, 'https://localhost:8443/testrestserver/rest/1/image/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (218, 'https://localhost:8443/testrestserver/rest/1/images/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (219, 'https://localhost:8443/testrestserver/rest/1/image/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (220, 'https://localhost:8443/testrestserver/rest/1/images/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (221, 'https://localhost:8443/testrestserver/rest/1/image/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (222, 'https://localhost:8443/testrestserver/rest/1/images/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (223, 'https://localhost:8443/testrestserver/rest/1/image/get/raw/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (224, 'https://localhost:8443/testrestserver/rest/1/image/get/raw/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (225, 'https://localhost:8443/testrestserver/rest/1/image/get/raw/\d+/thumbnail', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (226, 'https://localhost:8443/testrestserver/rest/1/topic/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (227, 'https://localhost:8443/testrestserver/rest/1/topic/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (228, 'https://localhost:8443/testrestserver/rest/1/topics/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (229, 'https://localhost:8443/testrestserver/rest/1/topics/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (230, 'https://localhost:8443/testrestserver/rest/1/topic/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (231, 'https://localhost:8443/testrestserver/rest/1/topics/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (232, 'https://localhost:8443/testrestserver/rest/1/topic/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (233, 'https://localhost:8443/testrestserver/rest/1/topics/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (234, 'https://localhost:8443/testrestserver/rest/1/topic/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (235, 'https://localhost:8443/testrestserver/rest/1/topics/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (236, 'https://localhost:8443/testrestserver/rest/1/topic/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (237, 'https://localhost:8443/testrestserver/rest/1/topic/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (238, 'https://localhost:8443/testrestserver/rest/1/topics/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (239, 'https://localhost:8443/testrestserver/rest/1/topics/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (240, 'https://localhost:8443/testrestserver/rest/1/topic/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (241, 'https://localhost:8443/testrestserver/rest/1/topics/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (242, 'https://localhost:8443/testrestserver/rest/1/topic/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (243, 'https://localhost:8443/testrestserver/rest/1/topics/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (244, 'https://localhost:8443/testrestserver/rest/1/topic/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (245, 'https://localhost:8443/testrestserver/rest/1/topics/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (246, 'https://localhost:8443/testrestserver/rest/1/topics/get/xml/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (247, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (248, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (249, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\d+/xml', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (250, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\d+/r/\d+/xml', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (251, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\d+/xmlContainedIn', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (252, 'https://localhost:8443/testrestserver/rest/1/topic/get/xml/\d+/xmlNoContainer', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (253, 'https://localhost:8443/testrestserver/rest/1/topic/get/html/\d+/html', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (254, 'https://localhost:8443/testrestserver/rest/1/topic/get/html/\d+/r/\d+/html', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (255, 'https://localhost:8443/testrestserver/rest/1/topics/get/atom/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (256, 'https://localhost:8443/testrestserver/rest/1/filter/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (257, 'https://localhost:8443/testrestserver/rest/1/filter/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (258, 'https://localhost:8443/testrestserver/rest/1/filters/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (259, 'https://localhost:8443/testrestserver/rest/1/filters/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (260, 'https://localhost:8443/testrestserver/rest/1/filter/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (261, 'https://localhost:8443/testrestserver/rest/1/filters/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (262, 'https://localhost:8443/testrestserver/rest/1/filter/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (263, 'https://localhost:8443/testrestserver/rest/1/filters/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (264, 'https://localhost:8443/testrestserver/rest/1/filter/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (265, 'https://localhost:8443/testrestserver/rest/1/filters/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (266, 'https://localhost:8443/testrestserver/rest/1/filter/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (267, 'https://localhost:8443/testrestserver/rest/1/filter/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (268, 'https://localhost:8443/testrestserver/rest/1/filters/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (269, 'https://localhost:8443/testrestserver/rest/1/filters/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (270, 'https://localhost:8443/testrestserver/rest/1/filter/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (271, 'https://localhost:8443/testrestserver/rest/1/filters/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (272, 'https://localhost:8443/testrestserver/rest/1/filter/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (273, 'https://localhost:8443/testrestserver/rest/1/filters/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (274, 'https://localhost:8443/testrestserver/rest/1/filter/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (275, 'https://localhost:8443/testrestserver/rest/1/filters/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (276, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (277, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (278, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (279, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (280, 'https://localhost:8443/testrestserver/rest/1/integerconstant/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (281, 'https://localhost:8443/testrestserver/rest/1/integerconstants/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (282, 'https://localhost:8443/testrestserver/rest/1/integerconstant/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (283, 'https://localhost:8443/testrestserver/rest/1/integerconstants/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (284, 'https://localhost:8443/testrestserver/rest/1/integerconstant/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (285, 'https://localhost:8443/testrestserver/rest/1/integerconstants/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (286, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (287, 'https://localhost:8443/testrestserver/rest/1/integerconstant/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (288, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (289, 'https://localhost:8443/testrestserver/rest/1/integerconstants/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (290, 'https://localhost:8443/testrestserver/rest/1/integerconstant/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (291, 'https://localhost:8443/testrestserver/rest/1/integerconstants/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (292, 'https://localhost:8443/testrestserver/rest/1/integerconstant/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (293, 'https://localhost:8443/testrestserver/rest/1/integerconstants/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (294, 'https://localhost:8443/testrestserver/rest/1/integerconstant/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (295, 'https://localhost:8443/testrestserver/rest/1/integerconstants/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (296, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (297, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (298, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (299, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (300, 'https://localhost:8443/testrestserver/rest/1/contentspec/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (301, 'https://localhost:8443/testrestserver/rest/1/contentspecs/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (302, 'https://localhost:8443/testrestserver/rest/1/contentspec/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (303, 'https://localhost:8443/testrestserver/rest/1/contentspecs/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (304, 'https://localhost:8443/testrestserver/rest/1/contentspec/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (305, 'https://localhost:8443/testrestserver/rest/1/contentspecs/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (306, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (307, 'https://localhost:8443/testrestserver/rest/1/contentspec/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (308, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (309, 'https://localhost:8443/testrestserver/rest/1/contentspecs/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (310, 'https://localhost:8443/testrestserver/rest/1/contentspec/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (311, 'https://localhost:8443/testrestserver/rest/1/contentspecs/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (312, 'https://localhost:8443/testrestserver/rest/1/contentspec/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (313, 'https://localhost:8443/testrestserver/rest/1/contentspecs/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (314, 'https://localhost:8443/testrestserver/rest/1/contentspec/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (315, 'https://localhost:8443/testrestserver/rest/1/contentspecs/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (316, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (317, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (318, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (319, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (320, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (321, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (322, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (323, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (324, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (325, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (326, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (327, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (328, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (329, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (330, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (331, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (332, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (333, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (334, 'https://localhost:8443/testrestserver/rest/1/contentspecnode/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (335, 'https://localhost:8443/testrestserver/rest/1/contentspecnodes/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (336, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/get/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (337, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/get/jsonp/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (338, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/get/jsonp/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (339, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/get/jsonp/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (340, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (341, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/update/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (342, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (343, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/create/jsonp', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (344, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/delete/jsonp/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (345, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/delete/jsonp/ids;(\d+;)*\d+;?', 'GET', true);

insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (346, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/get/json/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (347, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/get/json/\d+/r/\d+', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (348, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/get/json/all', 'GET', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (349, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/get/json/query;([-\w%~\.]+=[-\w%~\.]*;)*([-\w%~\.]+=[-\w%~\.]*;?)?', 'GET', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (350, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (351, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/update/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (352, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (353, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/create/json', 'POST', false);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (354, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadata/delete/json/\d+', 'DELETE', true);
insert into RS_ENDPOINT (ENDPOINT_ID, ENDPOINT_URL, ENDPOINT_METHOD, URL_REGEX) values (355, 'https://localhost:8443/testrestserver/rest/1/contentspecmetadatas/delete/json/ids;(\d+;)*\d+;?', 'DELETE', true);

insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 1);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 2);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 3);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 4);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 5);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 6);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 7);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 8);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 9);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 10);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 11);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 12);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 13);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 14);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 15);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 16);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 17);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 18);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 19);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 20);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 21);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 22);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 23);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 24);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 25);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 26);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 27);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 28);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 29);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 30);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 31);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 32);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 33);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 34);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 35);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 36);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 37);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 38);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 39);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 40);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 41);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 42);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 43);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 44);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 45);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 46);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 47);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 48);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 49);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 50);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 51);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 52);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 53);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 54);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 55);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 56);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 57);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 58);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 59);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 60);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 61);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 62);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 63);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 64);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 65);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 66);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 67);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 68);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 69);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 70);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 71);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 72);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 73);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 74);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 75);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 76);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 77);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 78);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 79);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 80);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 81);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 82);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 83);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 84);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 85);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 86);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 87);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 88);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 89);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 90);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 91);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 92);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 93);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 94);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 95);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 96);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 97);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 98);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 99);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 100);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 101);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 102);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 103);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 104);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 105);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 106);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 107);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 108);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 109);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 110);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 111);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 112);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 113);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 114);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 115);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 116);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 117);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 118);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 119);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 120);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 121);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 122);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 123);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 124);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 125);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 126);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 127);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 128);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 129);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 130);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 131);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 132);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 133);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 134);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 135);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 136);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 137);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 138);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 139);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 140);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 141);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 142);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 143);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 144);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 145);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 146);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 147);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 148);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 149);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 150);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 151);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 152);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 153);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 154);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 155);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 156);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 157);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 158);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 159);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 160);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 161);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 162);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 163);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 164);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 165);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 166);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 167);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 168);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 169);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 170);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 171);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 172);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 173);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 174);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 175);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 176);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 177);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 178);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 179);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 180);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 181);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 182);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 183);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 184);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 185);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 186);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 187);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 188);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 189);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 190);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 191);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 192);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 193);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 194);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 195);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 196);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 197);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 198);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 199);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 200);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 201);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 202);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 203);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 204);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 205);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 206);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 207);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 208);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 209);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 210);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 211);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 212);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 213);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 214);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 215);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 216);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 217);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 218);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 219);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 220);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 221);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 222);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 223);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 224);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 225);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 226);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 227);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 228);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 229);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 230);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 231);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 232);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 233);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 234);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 235);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 236);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 237);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 238);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 239);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 240);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 241);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 242);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 243);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 244);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 245);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 246);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 247);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 248);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 249);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 250);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 251);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 252);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 253);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 254);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 255);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 256);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 257);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 258);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 259);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 260);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 261);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 262);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 263);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 264);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 265);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 266);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 267);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 268);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 269);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 270);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 271);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 272);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 273);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 274);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 275);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 276);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 277);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 278);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 279);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 280);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 281);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 282);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 283);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 284);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 285);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 286);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 287);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 288);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 289);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 290);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 291);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 292);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 293);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 294);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 295);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 296);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 297);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 298);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 299);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 300);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 301);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 302);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 303);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 304);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 305);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 306);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 307);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 308);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 309);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 310);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 311);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 312);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 313);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 314);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 315);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 316);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 317);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 318);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 319);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 320);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 321);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 322);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 323);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 324);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 325);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 326);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 327);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 328);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 329);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 330);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 331);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 332);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 333);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 334);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 335);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 336);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 337);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 338);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 339);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 340);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 341);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 342);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 343);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 344);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 345);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 346);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 347);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 348);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 349);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 350);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 351);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 352);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 353);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 354);
insert into RS_SCOPE_RS_ENDPOINT (SCOPE_ID, ENDPOINT_ID) values (1, 355);

alter table `RS_SCOPE_RS_ENDPOINT` add constraint `FK_RS_SCOPE_RS_ENDPOINT_SCOPE_ID` FOREIGN KEY (`SCOPE_ID`) REFERENCES `RS_SCOPE` (`SCOPE_ID`), add constraint `FK_RS_SCOPE_RS_ENDPOINT_ENDPOINT_ID` FOREIGN KEY (`ENDPOINT_ID`) REFERENCES `RS_ENDPOINT` (`ENDPOINT_ID`);
