ALTER TABLE  `Skynet`.`TopicToPropertyTag_AUD` ADD INDEX `TopicID` ( `TopicID` ), ADD INDEX `PropertyTagID` ( `PropertyTagID` );
ALTER TABLE  `Skynet`.`TopicToPropertyTag` ADD INDEX  `PropertyTagToValue` (  `Value` ( 32 ) ,  `PropertyTagID` );
ALTER TABLE  `Skynet`.`TopicToPropertyTag_AUD` ADD INDEX  `PropertyTagToValue` (  `Value` ( 32 ) ,  `PropertyTagID` );
ALTER TABLE  `Skynet`.`TopicToTag_AUD` ADD INDEX `TagID` ( `TagID` ), ADD INDEX  `TopicID` ( `TopicID` );
ALTER TABLE  `Skynet`.`TopicToTopicSourceURL_AUD` ADD INDEX  `TopicID` ( `TopicID` ), ADD INDEX `TopicSourceURLID` ( `TopicSourceURLID` );
ALTER TABLE  `Skynet`.`TopicToTopic_AUD` ADD INDEX `MainTopicID` ( `MainTopicID` ), ADD INDEX `RelatedTopicID` ( `RelatedTopicID` );
ALTER TABLE  `Skynet`.`TopicToBugzillaBug_AUD` ADD INDEX `TopicID` ( `TopicID` ), ADD INDEX `BugzillaBugID` ( `BugzillaBugID` );
ALTER TABLE  `Skynet`.`TranslatedTopicData_AUD` ADD INDEX `TranslatedTopicID` ( `TranslatedTopicID` );
ALTER TABLE	 `Skynet`.`TranslatedTopicString_AUD` ADD INDEX `TranslatedTopicData` (`TranslatedTopicDataID`);
ALTER TABLE  `Skynet`.`FilterCategory_AUD` ADD INDEX `FilterID` ( `FilterID` );
ALTER TABLE  `Skynet`.`FilterTag_AUD` ADD INDEX `FilterID` ( `FilterID` );
ALTER TABLE  `Skynet`.`FilterLocale_AUD` ADD INDEX `FilterID` ( `FilterID` );
ALTER TABLE  `Skynet`.`FilterOption_AUD` ADD INDEX `FilterID` ( `FilterID` );
ALTER TABLE  `Skynet`.`LanguageImage_AUD` ADD INDEX `ImageFileID` ( `ImageFileID` );
ALTER TABLE  `Skynet`.`TagToPropertyTag_AUD` ADD INDEX  `TagID` ( `TagID` ), ADD INDEX `PropertyTagID` ( `PropertyTagID` );
ALTER TABLE  `Skynet`.`TagToProject_AUD` ADD INDEX `TagID` ( `TagID` ), ADD INDEX `ProjectID` ( `ProjectID` );
ALTER TABLE  `Skynet`.`TagToCategory_AUD` ADD INDEX `TagID` ( `TagID` ), ADD INDEX `CategoryID` ( `CategoryID` );
ALTER TABLE  `Skynet`.`TagToTag_AUD` ADD INDEX `PrimaryTagID` ( `PrimaryTagID` ), ADD INDEX `SecondaryTagID` ( `SecondaryTagID` );
ALTER TABLE  `Skynet`.`PropertyTagToPropertyTagCategory_AUD` ADD INDEX  `PropertyTagID` ( `PropertyTagID` ), ADD INDEX `PropertyTagCategoryID` ( `PropertyTagCategoryID` );
ALTER TABLE  `Skynet`.`CSNodeToCSTranslatedString_AUD` ADD INDEX  `CSNodeID` ( `CSNodeID` ), ADD INDEX `CSTranslatedStringID` (  `CSTranslatedStringID` );
ALTER TABLE  `Skynet`.`CSNodeToPropertyTag_AUD` ADD INDEX  `CSNodeID` ( `CSNodeID` ), ADD INDEX `PropertyTagID` ( `PropertyTagID` );
ALTER TABLE  `Skynet`.`CSNodeToCSNode_AUD` ADD INDEX `MainNodeID` ( `MainNodeID` ), ADD INDEX `RelatedNodeID` ( `RelatedNodeID` );
ALTER TABLE  `Skynet`.`ContentSpecToPropertyTag_AUD` ADD INDEX `ContentSpecID` ( `ContentSpecID` ), ADD INDEX `PropertyTagID` ( `PropertyTagID` );
ALTER TABLE  `Skynet`.`ContentSpecToTag_AUD` ADD INDEX `TagID` ( `TagID` ), ADD INDEX `ContentSpecID` ( `ContentSpecID` );
ALTER TABLE  `Skynet`.`ContentSpecToProject_AUD` ADD INDEX `ProjectID` ( `ProjectID` ), ADD INDEX `ContentSpecID` ( `ContentSpecID` );
ALTER TABLE  `Skynet`.`ContentSpecToCSMetaData_AUD` ADD INDEX `CSMetaDataID` ( `ContentSpecMetaDataID` ), ADD INDEX `ContentSpecID` ( `ContentSpecID` );
ALTER TABLE  `Skynet`.`UserRole_AUD` ADD INDEX `RoleID` ( `RoleNameID` ), ADD INDEX `UserID` ( `UserNameID` );
ALTER TABLE  `Skynet`.`RoleToRole_AUD` ADD INDEX `PrimaryRoleID` ( `PrimaryRole` ), ADD INDEX `SecondaryRoleID` ( `SecondaryRole` );
